### ISSUE TITLE
Fusion integration stoped working

### ISSUE THREAD

**Issue by NickBootOne** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#13]
FusionSolar integration in Home Assistant stoped working after Site upgrade that had finished on 30 december.
Kiosk site work but no info is visible in Home Assistant.

Tried generating a new Kiosk link but that didn't help.

**Comment by tobber72** [comment]
It looks like they have changed to region02eu5.fusionsolar.huawei.com instead of eu5.fusionsolar.huawei.com for the kiosk site. As a temporary solution, you can change this in the file /config/custom_components/fusion_solar_kiosk/sensor.py (with the File editor Add-on for example) and then restart HA.

**Comment by NickBootOne** [comment]
Thanks @tobber72  this workaround works.

**Comment by Pme1159** [comment]
Hello tobber72. Since the update of the Huawei site, I lost the data in HA.
I tried to replace the address in the line 36 of the file /config/custom_components/fusion_solar_kiosk/sensor.py and restarting HA but in my case, it doesn't work. I thank you in advance for your help.

```
async def async_setup_platform(hass, config, async_add_entities, discovery_info=None):
    async def async_update_data():
        """Fetch data"""
        api = FusionSolarKioksApi('https://region01eu5.fusionsolar.huawei.com')
        data = {}
        for kiosk in config[CONF_KIOSKS]:
            data[kiosk['id']] = {
                ATTR_DATA_REALKPI: await hass.async_add_executor_job(api.getRealTimeKpi, kiosk['id'])
            }

```

Best wishes for 2022.

**Comment by tobber72** [comment]
Strange, can you verify that the following endpoint returns json-data if you try it out in your regular web browser:

https://region03eu5.fusionsolar.huawei.com/rest/pvms/web/kiosk/v1/station-kiosk-file?kk=ReplaceWithYourKioskKey

If it returns 'null' or similar I think it is the wrong kiosk site or key for your plant address.

**Comment by Pme1159** [comment]
Thank you
https://region01eu5.fusionsolar.huawei.com/rest/pvms/web/kiosk/v1/station-kiosk-file?kk=XXXXX returns json data :like this 
`{"data":"{&quot;powerCurve&quot;:{&quot;xAxis&quot;:[&quot;00:00&quot;,&quot;00:05&quot;,&quot;00:10&quot;,&quot;00:15&quot;,&quot;00:20&quot;,&quot;00:25&quot;,&quot;00:30&quot;,&quot;00:35&quot;,&quot;00:40&quot;,&quot;00:45&quot;,&quot;00:50&quot;,&quot;00:55&quot;,&quot;01:00&quot;,&quot;01:05&quot;,&quot;01:10&quot;,&quot;01:15&quot;,&quot;01:20&quot;,&quot;01:25&quot;,&quot;01:30&quot;,&quot;01:35&quot;,&quot;01:40&quot;,&quot;01:45&quot;,&quot;01:50&quot;,&quot;01:55&quot;,&quot;02:00&quot;,&quot;02:05&quot;,&quot;02:10&quot;,&quot;02:15&quot;,&quot;02:20&quot;,&quot;02:25&quot;,&quot;02:30&quot;,&quot;02:35&quot;,&quot;02:40&quot;,&quot;02:45&quot;,&quot;02:50&quot;,&quot;02:55&quot;,&quot;03:00&quot;,&quot;03:05&quot;,&quot;03:10&quot;,&quot;03:15&quot;,&quot;03:20&quot;,&quot;03:25&quot;,&quot;03:30&quot;,&quot;03:35&quot;,&quot;03:40&quot;,&quot;03:45&quot;,&quot;03:50&quot;,&quot;03:55&quot;,&quot;04:00&quot;,&quot;04:05&quot;,&quot;04:10&quot;,&quot;04:15&quot;,&quot;04:20&quot;,&quot;04:25&quot;,&quot;04:30&quot;,&quot;04:35&quot;,&quot;04:40&quot;,&quot;04:45&quot;,&quot;04:50&quot;,&quot;04:55&quot;,&quot;05:00&quot;,&quot;05:05&quot;,&quot;05:10&quot;,&quot;05:15&quot;,&quot;05:20&quot;,&quot;05:25&quot;,&quot;05:30&quot;,&quot;05:35&quot;,&quot;05:40&quot;,&quot;05:45&quot;,&quot;05:50&quot;,&quot;05:55&quot;,&quot;06:00&quot;,&quot;06:05&quot;,&quot;06:10&quot;,&quot;06:15&quot;,&quot;06:20&quot;,&quot;06:25&quot;,&quot;06:30&quot;,&quot;06:35&quot;,&quot;06:40&quot;,&quot;06:45&quot;,&quot;06:50&quot;,&quot;06:55&quot;,&quot;07:00&quot;,&quot;07:05&quot;,&quot;07:10&quot;,&quot;07:15&quot;,&quot;07:20&quot;,&quot;07:25&quot;,&quot;07:30&quot;,&quot;07:35&quot;,&quot;07:40&quot;,&quot;07:45&quot;,&quot;07:50&quot;,&quot;07:55&quot;,&quot;08:00&quot;,&quot;08:05&quot;,&quot;08:10&quot;,&quot;08:15&quot;,&quot;08:20&quot;,&quot;08:25&quot;,&quot;08:30&quot;,&quot;08:35&quot;,&quot;08:40&quot;,&quot;08:45&quot;,&quot;08:50&quot;,&quot;08:55&quot;,&quot;09:00&quot;,&quot;09:05&quot;,&quot;09:10&quot;,&quot;09:15&quot;,&quot;09:20&quot;,&quot;09:25&quot;,&quot;09:30&quot;,&quot;09:35&quot;,&quot;09:40&quot;,&quot;09:45&quot;,&quot;09:50&quot;,&quot;09:55&quot;,&quot;10:00&quot;,&quot;10:05&quot;,&quot;10:10&quot;,&quot;10:15&quot;,&quot;10:20&quot;,&quot;10:25&quot;,&quot;10:30&quot;,&quot;10:35&quot;,&quot;10:40&quot;,&quot;10:45&quot;,&quot;10:50&quot;,&quot;10:55&quot;,&quot;11:00&quot;,&quot;11:05&quot;,&quot;11:10&quot;,&quot;11:15&quot;,&quot;11:20&quot;,&quot;11:25&quot;,&quot;11:30&quot;,&quot;11:35&quot;,&quot;11:40&quot;,&quot;11:45&quot;,&quot;11:50&quot;,&quot;11:55&quot;,&quot;12:00&quot;,&quot;12:05&quot;,&quot;12:10&quot;,&quot;12:15&quot;,&quot;12:20&quot;,&quot;12:25&quot;,&quot;12:30&quot;,&quot;12:35&quot;,&quot;12:40&quot;,&quot;12:45&quot;,&quot;12:50&quot;,&quot;12:55&quot;,&quot;13:00&quot;,&quot;13:05&quot;,&quot;13:10&quot;,&quot;13:15&quot;,&quot;13:20&quot;,&quot;13:25&quot;,&quot;13:30&quot;,&quot;13:35&quot;,&quot;13:40&quot;,&quot;13:45&quot;,&quot;13:50&quot;,&quot;13:55&quot;,&quot;14:00&quot;,&quot;14:05&quot;,&quot;14:10&quot;,&quot;14:15&quot;,&quot;14:20&quot;,&quot;14:25&quot;,&quot;14:30&quot;,&quot;14:35&quot;,&quot;14:40&quot;,&quot;14:45&quot;,&quot;14:50&quot;,&quot;14:55&quot;,&quot;15:00&quot;,&quot;15:05&quot;,&quot;15:10&quot;,&quot;15:15&quot;,&quot;15:20&quot;,&quot;15:25&quot;,&quot;15:30&quot;,&quot;15:35&quot;,&quot;15:40&quot;,&quot;15:45&quot;,&quot;15:50&quot;,&quot;15:55&quot;,&quot;16:00&quot;,&quot;16:05&quot;,&quot;16:10&quot;,&quot;16:15&quot;,&quot;16:20&quot;,&quot;16:25&quot;,&quot;16:30&quot;,&quot;16:35&quot;,&quot;16:40&quot;,&quot;16:45&quot;,&quot;16:50&quot;,&quot;16:55&quot;,&quot;17:00&quot;,&quot;17:05&quot;,&quot;17:10&quot;,&quot;17:15&quot;,&quot;17:20&quot;,&quot;17:25&quot;,&quot;17:30&quot;,&quot;17:35&quot;,&quot;17:40&quot;,&quot;17:45&quot;,&quot;17:50&quot;,&quot;17:55&quot;,&quot;18:00&quot;,&quot;18:05&quot;,&quot;18:10&quot;,&quot;18:15&quot;,&quot;18:20&quot;,&quot;18:25&quot;,&quot;18:30&quot;,&quot;18:35&quot;,&quot;18:40&quot;,&quot;18:45&quot;,&quot;18:50&quot;,&quot;18:55&quot;,&quot;19:00&quot;,&quot;19:05&quot;,&quot;19:10&quot;,&quot;19:15&quot;,&quot;19:20&quot;,&quot;19:25&quot;,&quot;19:30&quot;,&quot;19:35&quot;,&quot;19:40&quot;,&quot;19:45&quot;,&quot;19:50&quot;,&quot;19:55&quot;,&quot;20:00&quot;,&quot;20:05&quot;,&quot;20:10&quot;,&quot;20:15&quot;,&quot;20:20&quot;,&quot;20:25&quot;,&quot;20:30&quot;,&quot;20:35&quot;,&quot;20:40&quot;,&quot;20:45&quot;,&quot;20:50&quot;,&quot;20:55&quot;,&quot;21:00&quot;,&quot;21:05&quot;,&quot;21:10&quot;,&quot;21:15&quot;,&quot;21:20&quot;,&quot;21:25&quot;,&quot;21:30&quot;,&quot;21:35&quot;,&quot;21:40&quot;,&quot;21:45&quot;,&quot;21:50&quot;,&quot;21:55&quot;,&quot;22:00&quot;,&quot;22:05&quot;,&quot;22:10&quot;,&quot;22:15&quot;,&quot;22:20&quot;,&quot;22:25&quot;,&quot;22:30&quot;,&quot;22:35&quot;,&quot;22:40&quot;,&quot;22:45&quot;,&quot;22:50&quot;,&quot;22:55&quot;,&quot;23:00&quot;,&quot;23:05&quot;,&quot;23:10&quot;,&quot;23:15&quot;,&quot;23:20&quot;,&quot;23:25&quot;,&quot;23:30&quot;,&quot;23:35&quot;,&quot;23:40&quot;,&quot;23:45&quot;,&quot;23:50&quot;,&quot;23:55&quot;],&quot;currentPower&quot;:&quot;0.00&quot;,&quot;activePower&quot;:[&quot;-&quot;,&quot;-&quot;,&quot;-&quot;,&quot;-&quot;,&quot;-&quot;,&quot;-&quot;,&quot;-&quot;,&quot;-&quot;,&quot;-&quot;,&quot;-...`

**Comment by Pme1159** [comment]
But the developments tools in HA shows : 
![image](https://user-images.githubusercontent.com/59808783/147888622-70d2b4be-7d85-4cf1-b315-0f848c17ef87.png)

**Comment by Pme1159** [comment]
I tried with  ` api = FusionSolarKioksApi('https://region01eu5.fusionsolar.huawei.com/rest/pvms/web/kiosk/v1') `in the line 36
but I get then the following error in the log of HA : 
```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.fusion_solar_kiosk.sensor
Source: custom_components/fusion_solar_kiosk/fusion_solar_kiosk_api.py:32
Integration: FusionSolar Kiosk (documentation, issues)
First occurred: 21:37:55 (1 occurrences)
Last logged: 21:37:55

Unexpected error fetching FusionSolarKiosk data: Expecting value: line 6 column 1 (char 5)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/fusion_solar_kiosk/sensor.py", line 40, in async_update_data
    ATTR_DATA_REALKPI: await hass.async_add_executor_job(api.getRealTimeKpi, kiosk['id'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fusion_solar_kiosk/fusion_solar_kiosk_api.py", line 32, in getRealTimeKpi
    jsonData = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 6 column 1 (char 5)

```

**Comment by tobber72** [comment]
> I tried with `api = FusionSolarKioksApi('https://region01eu5.fusionsolar.huawei.com/rest/pvms/web/kiosk/v1')`in the line 36 but I get then the following error in the log of HA :

You shall only have the host part of the url (https://region01eu5.fusionsolar.huawei.com) in the sensor.py file. The rest of the url (/rest/pvms/web/kiosk/v1 and so on) is added in the fusion_solar_kiosk_api.py file.

Maybe you can try enabling more logging in the configuration.yaml file and see if you get any clue why it does not work for you.

```
logger:
  default: info
  logs:
    custom_components.fusion_solar_kiosk: debug
```

By the way, do you have the latest version (v2.1.0) of "Home-Assisant-FusionSolar-Kiosk" installed via HACS? :-)

**Comment by Pme1159** [comment]
I confirm. V2.1.0. installed via HACS.
I have this in the log "core" : 
`2022-01-03 10:45:20 DEBUG (MainThread) [custom_components.fusion_solar_kiosk.sensor] Finished fetching FusionSolarKiosk data in 0.182 seconds (success: True)`

**Comment by adischmidt** [comment]
I had the same issue, running v2.1.0 via HACS and HA Home Assistant 2021.11.2 (core).
There are 2 files where you need to make changes:

- homeassistant/custom_components/fusion_solar_kiosk/sensor.py, line 36
replace <api = FusionSolarKioksApi('https://eu5.fusionsolar.huawei.com')>
with <api = FusionSolarKioksApi('https://**region5**eu5.fusionsolar.huawei.com')>

- homeassistant/custom_components/fusion_solar_kiosk/fusion_solar_kiosk_api.py, line 22
replace <url = self._host + '/rest/pvms/web/kiosk/v1/station-kiosk-file?kk=' + id>
with <url = self._host + '/pvmswebsite/nologin/assets/build/index.html#/kiosk?kk=' + id>

Ignore the "<" & ">" characters, just used them to enclose the code.  After these changes and restarting my HA, all works fine.

**Comment by Pme1159** [comment]
Hello, I did it but I have now the following error message in the log : 
```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.fusion_solar_kiosk.sensor
Source: custom_components/fusion_solar_kiosk/fusion_solar_kiosk_api.py:32
Integration: FusionSolar Kiosk (documentation, issues)
First occurred: 00:38:24 (113 occurrences)
Last logged: 09:58:24

Unexpected error fetching FusionSolarKiosk data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/fusion_solar_kiosk/sensor.py", line 40, in async_update_data
    ATTR_DATA_REALKPI: await hass.async_add_executor_job(api.getRealTimeKpi, kiosk['id'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fusion_solar_kiosk/fusion_solar_kiosk_api.py", line 32, in getRealTimeKpi
    jsonData = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
I also trie to remove then to reinstall Fusion Solar always through HACS but I have the same issue.
Pascal

**Comment by Pme1159** [comment]
I also tried to change the language of the kiosk file in Fusion Solar to English but it doesn't change anything.

**Comment by tobber72** [comment]
> I also tried to change the language of the kiosk file in Fusion Solar to English but it doesn't change anything.

At the moment I unfortunately have run out of ideas to solve this problem for you but I wish you all the best and that you find a solution so you can use the integration again and if I come up with something I will try to get in touch :-)

**Comment by tijsverkoyen** [comment]
@tobber72 of @NickBootOne can someone confirm? If it is not working I suspect that I need to make the url of the kiosk configurable, because everybody can get another zone.
If possible could you share your full kiosk url with me please?

**Comment by adischmidt** [comment]
You have changed the URL in the sensor.py file, but my kiosk URL is like "https://region03eu5.fusionsolar.huawei.com", in your file it's "https://region04eu5.fusionsolar.huawei.com" so it's not working for me.
Also in the fusion_solar_kiosk_api.py file, the URL is in the old format.

**Comment by tijsverkoyen** [comment]
Ok, thx.
If I find the time later this week/next week I will try to make the url configurable.

**Comment by Pme1159** [comment]
Hello Tijs,
I tried to use the new version by changing the sensor.py and the fusion_solar_kiosk_api.py files but without success.
My api begins with : 
`https://region01eu5.fusionsolar.huawei.com/pvmswebsite/nologin/assets/build/index.html#/kiosk?kk=`
I of course also changed my configuration.yaml with the correct code (end of the api).
Thank you for your support.
Pascal

**Comment by Pme1159** [comment]
Done by email.

**Comment by adischmidt** [comment]
Done by email too.

**Comment by Michun** [comment]
For me it is region02, so it is differen

**Comment by adischmidt** [comment]
Confirm - it's working now.  Thank you for your efforts!

**Comment by Pme1159** [comment]
Thank you !

**Comment by tobber72** [comment]
Thank you for your efforts with the new version @tijsverkoyen !

**Comment by tijsverkoyen** [comment]
No problem!
