### ISSUE TITLE
Retrieving the data failed with failCode: 306, data: {'failCode': 306, 'immediately': True, 'message': 'USER_MUST_RELOGIN'}

### ISSUE THREAD

**Issue by Unifex4** [tijsverkoyen/Home-Assisant-FusionSolar-Kiosk#5]
Hi,
Great idea and I would like to get this working, but i get the error above. 
Is this HACS integration still working as intended?
Have i set the integration up correctly?

I'm in australia and my local kiosk server is sg5 not eu5 so i changed line 36 of sensor.py to read -
        api = FusionSolarKioksApi('https://sg5.fusionsolar.huawei.com')

My kiosk link is in this format (the "id" is 10 charachters with a combinations of upper and lower case characters and numbers) - 

https://sg5.fusionsolar.huawei.com/singleKiosk.html?kk=xXX#xxxx#X

The configuration.yaml entry example on your page was not accepted in the file editor due to "bad indentation" so mine looks like ("name" is indented more) - 
```
sensor:
  - platform: fusion_solar_kiosk
    kiosks:
        - id: "xXX#xxxx#X"
          name: "A readable name for the plant"
```
I see the "Sensor" and 5 entities (Real-time Power, etc) in the Lovelace overview, but they show as "Unavailable"

Log Page info - 
(Note - Officejet 6600 Warning is unrelated (I think))
```
Error doing job: Task exception was never retrieved
10:12:42 AM – (ERROR) FusionSolar Kiosk (custom integration) - message first occurred at 9:47:42 AM and shows up 6 times
Retrieving the data failed with failCode: 306, data: {'failCode': 306, 'immediately': True, 'message': 'USER_MUST_RELOGIN'}
10:12:42 AM – (ERROR) FusionSolar Kiosk (custom integration) - message first occurred at 9:42:42 AM and shows up 7 times
Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
9:52:49 AM – (WARNING) helpers/template.py - message first occurred at 9:43:29 AM and shows up 7 times
Config entry 'Officejet 6600 [081EB4]' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
9:42:49 AM – (WARNING) config_entries.py
Error adding entities for domain sensor with platform fusion_solar_kiosk
9:42:42 AM – (ERROR) Sensor (custom integration) - message first occurred at 9:42:42 AM and shows up 2 times
Error adding entities for domain sensor with platform fusion_solar_kiosk
9:42:42 AM – (ERROR) Sensor (custom integration) - message first occurred at 9:42:42 AM and shows up 4 times
You are using a custom integration fusion_solar_kiosk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
9:42:41 AM – (WARNING) loader.py
```
Full Log output - 
```
2021-05-17 09:42:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 09:42:41 WARNING (MainThread) [homeassistant.loader] You are using a custom integration fusion_solar_kiosk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 09:42:42 ERROR (SyncWorker_0) [custom_components.fusion_solar_kiosk.fusion_solar_kiosk_api] Retrieving the data failed with failCode: 306, data: {'failCode': 306, 'immediately': True, 'message': 'USER_MUST_RELOGIN'}
2021-05-17 09:42:42 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fusion_solar_kiosk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 98, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'realTimePower'
2021-05-17 09:42:42 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fusion_solar_kiosk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 58, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'dailyEnergy'
2021-05-17 09:42:42 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fusion_solar_kiosk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 58, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'monthEnergy'
2021-05-17 09:42:42 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fusion_solar_kiosk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 58, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'yearEnergy'
2021-05-17 09:42:42 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform fusion_solar_kiosk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 58, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'cumulativeEnergy'
2021-05-17 09:42:42 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fusion_solar_kiosk platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 239, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 98, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'realTimePower'
2021-05-17 09:42:49 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Officejet 6600 [081EB4]' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2021-05-17 09:43:29 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-05-17 09:43:29 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-05-17 09:43:29 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-05-17 09:43:29 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-05-17 09:43:29 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-05-17 09:47:42 ERROR (SyncWorker_3) [custom_components.fusion_solar_kiosk.fusion_solar_kiosk_api] Retrieving the data failed with failCode: 306, data: {'failCode': 306, 'immediately': True, 'message': 'USER_MUST_RELOGIN'}
2021-05-17 09:47:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 127, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 259, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 319, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 98, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'realTimePower'
2021-05-17 09:52:42 ERROR (SyncWorker_4) [custom_components.fusion_solar_kiosk.fusion_solar_kiosk_api] Retrieving the data failed with failCode: 306, data: {'failCode': 306, 'immediately': True, 'message': 'USER_MUST_RELOGIN'}
2021-05-17 09:52:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 127, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 259, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 319, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 98, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'realTimePower'
2021-05-17 09:52:49 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-05-17 09:52:49 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-05-17 09:57:42 ERROR (SyncWorker_1) [custom_components.fusion_solar_kiosk.fusion_solar_kiosk_api] Retrieving the data failed with failCode: 306, data: {'failCode': 306, 'immediately': True, 'message': 'USER_MUST_RELOGIN'}
2021-05-17 09:57:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 127, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 259, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 319, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 98, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'realTimePower'
2021-05-17 10:02:42 ERROR (SyncWorker_4) [custom_components.fusion_solar_kiosk.fusion_solar_kiosk_api] Retrieving the data failed with failCode: 306, data: {'failCode': 306, 'immediately': True, 'message': 'USER_MUST_RELOGIN'}
2021-05-17 10:02:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 127, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 259, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 319, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _stringify_state
state = self.state
File "/config/custom_components/fusion_solar_kiosk/__init__.py", line 98, in state
return float(self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI][self._attribute]) if self.coordinator.data[self._kioskId][ATTR_DATA_REALKPI] else None
KeyError: 'realTimePower'
```

**Comment by Unifex4** [comment]
Working now!
I'm not sure what changed?
But I now have readings on the sensor :)
